language: python
install: pip install tox
script: tox

jobs:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
      install: pip install tox coveralls
      after_success: coveralls
